# Generated by Django 5.2.4 on 2025-08-02 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('bin_full', 'Bin Full'), ('bin_overflow', 'Bin Overflow'), ('sensor_malfunction', 'Sensor Malfunction'), ('low_battery', 'Low Battery'), ('maintenance_due', 'Maintenance Due'), ('unusual_activity', 'Unusual Activity')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(help_text='Unique bin identifier', max_length=50, unique=True)),
                ('bin_size', models.CharField(choices=[('small', 'Small (50L)'), ('medium', 'Medium (120L)'), ('large', 'Large (240L)'), ('industrial', 'Industrial (1000L+)')], default='medium', max_length=20)),
                ('capacity_liters', models.IntegerField(help_text='Bin capacity in liters')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_emptied', models.DateTimeField(blank=True, null=True)),
                ('maintenance_due', models.DateField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, help_text='QR code for bin identification', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bin_id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Repair'), ('calibration', 'Sensor Calibration'), ('battery_replacement', 'Battery Replacement'), ('software_update', 'Software Update'), ('inspection', 'Routine Inspection')], max_length=30)),
                ('description', models.TextField()),
                ('parts_used', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('before_photos', models.ImageField(blank=True, null=True, upload_to='maintenance/before/')),
                ('after_photos', models.ImageField(blank=True, null=True, upload_to='maintenance/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('battery_level', models.IntegerField(default=100, help_text='Battery level percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calibration_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sensor_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_anomaly', models.BooleanField(default=False, help_text='Flagged as unusual reading')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fill_level', 'Fill Level Sensor'), ('weight', 'Weight Sensor'), ('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('gas', 'Gas Detection Sensor'), ('motion', 'Motion Sensor')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(help_text='Measurement unit (e.g., %, kg, °C)', max_length=20)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=100)),
            ],
        ),
    ]
