# Generated by Django 5.2.4 on 2025-08-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='waste.location'),
        ),
        migrations.AddField(
            model_name='bin',
            name='waste_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastecategory'),
        ),
        migrations.AddField(
            model_name='alert',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.bin'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='sensors.bin'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensor',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.bin'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensortype'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor', '-timestamp'], name='sensors_sen_sensor__d03b31_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['-timestamp'], name='sensors_sen_timesta_557074_idx'),
        ),
    ]
