# Generated by Django 5.2.4 on 2025-08-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('recycling', 'Recycling Achievement'), ('consistency', 'Consistency'), ('community', 'Community Participation'), ('milestone', 'Milestone'), ('special', 'Special Event')], max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class as fallback', max_length=50)),
                ('color', models.CharField(default='#4CAF50', help_text='Hex color code', max_length=7)),
                ('points_required', models.IntegerField(default=0, help_text='Minimum points to earn this badge')),
                ('is_active', models.BooleanField(default=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leaderboard_type', models.CharField(choices=[('points_weekly', 'Weekly Points'), ('points_monthly', 'Monthly Points'), ('points_all_time', 'All-Time Points'), ('recycling_streak', 'Longest Recycling Streak'), ('weight_recycled', 'Most Weight Recycled')], max_length=20)),
                ('timeframe', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all_time', 'All Time')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['leaderboard_type', 'timeframe'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('discount', 'Discount Coupon'), ('voucher', 'Gift Voucher'), ('merchandise', 'Merchandise'), ('service', 'Service Credit'), ('donation', 'Charity Donation')], max_length=20)),
                ('points_cost', models.IntegerField()),
                ('monetary_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/')),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redemption_code', models.CharField(max_length=50, unique=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('points_spent', models.IntegerField()),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=100, help_text='Progress percentage when earned')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
